syntax = "proto3";
package bzd.users.auth;

service AuthService {
    rpc Join(JoinRequest) returns (JoinResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Complete(CompleteRequest) returns (CompleteResponse);
}

message JoinRequest {
    optional string login = 101;
}

message JoinResponse {
    optional string response = 101;
}

message LoginRequest {
    optional string request = 101;
}

message LoginResponse {
    optional string jwt = 101;
}

message CompleteRequest {
    optional string request = 101;
}

message CompleteResponse {
    optional string jwt = 101;
}
